### ISSUE TITLE
Managing /etc/hosts on the host only (not on guests)?

### ISSUE THREAD

**Issue by tknerr** [smdahlen/vagrant-hostmanager#108]
Is it possible to have the plugin manage only the `/etc/hosts` on the host machine, but not on the guest?

Use case is that I'm using Chef for provisioning on the guest which already takes care of the hosts file. It would be useful though to access the Vagrant VMs via their hostname from the host.

Probably this is already possible, but looking at the available config options it is at least not clear to me.

**Comment by ekohlwey** [comment]
+1

**Comment by HadesArchitect** [comment]
Any updates? We also need this option. Thanks!
