### ISSUE TITLE
Tagging a new release

### ISSUE THREAD

**Issue by dancras** [smdahlen/vagrant-hostmanager#122]
Just wondering when you plan to tag a new release? Been waiting for a fix that is in master for a few months now. I know I can manually install the development version but that just adds an overhead to a different part of our process =) Thanks

**Comment by ccope** [comment]
Bump, my team also needs to run HEAD to fix #60. Tagging a release would make deployment easier.

**Comment by wunc** [comment]
+1
OSX 10.10.4 is out and reverted back to mDNSResponder, so #80 is relevant again. A new release would be much appreciated!

**Comment by dancras** [comment]
I think running the script for the workaround has reached muscle memory at this point.. A release version would be much appreciated still :smile: Is there something we can help with to move this along?

**Comment by seth-reeser** [comment]
v1.6.0 has been released.

**Comment by dancras** [comment]
Much appreciated!
