### ISSUE TITLE
Unable to install - "Error while installing nokogiri"

### ISSUE THREAD

**Issue by toby-griffiths** [smdahlen/vagrant-hostmanager#126]
I'm trying to install this plugin, but it keeps erroring.  I've tried as the user, with & without sudo, as well as as an admin user, but I get the following error...
```
An error occurred while installing nokogiri (1.6.5), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.5'` succeeds before bundling.
```
I have installed the nokogiri gem manually, without any problems (using sudo).

Any idea why I'm having problems, or better still, how to resolve this issue?

Thanks in advance.

**Comment by toby-griffiths** [comment]
I've manage to get this working now, by installing the latest version of Vagrant...

```
  # Vagrant
  class { 'vagrant':
    version    => '1.7.1',
    completion => true,
  }
  vagrant::plugin { 'vagrant-hostmaster': }
```

**Comment by settermjd** [comment]
I had the same issue and the latest version resolved it for me as well.
