### ISSUE TITLE
CoreOS + vagrant hostmanager error: SCP did not finish successfully

### ISSUE THREAD

**Issue by tleyden** [smdahlen/vagrant-hostmanager#127]
I posted to the Vagrant google group:

https://groups.google.com/d/msg/vagrant-up/j6PyKmL1L8Y/6lVTyVBmmOAJ

does it look like an issue with vagrant-hostmanager?  Any tips on how to debug this?

**Comment by AntouanK** [comment]
That did eliminate the errors, but my OSX /etc/hosts file remains as is.
Even if I manually run `vagrant hostmanager` in the folder I have my Vagrantfile, all I get is this message
```
[core-develop-01] Updating /etc/hosts file...
```
and that's it. /etc/hosts is never updated.

**Comment by aglahe** [comment]
I did a "brute force," ugly way.  After approx. line 126 (config.vm.network :private_network, ip: ip) I added the following below:

(1..$num_instances).each do|v|
  config.vm.provision "shell" do |s|
    s.inline = "echo $1 $2 >> /etc/hosts"
    s.args = ["172.17.8.#{v+100}", "%s-%02d" % [$instance_name_prefix, v]]
  end
end

Not a ruby guy at all, but it works.  Cheers.

**Comment by seth-reeser** [comment]
I will create a pre-release to fix this issue - who wants to volunteer to test for me?

**Comment by seth-reeser** [comment]
Please upgrade to the latest vagrant and vagrant-hostmanager version. If the problem still persists, please post your vagrant file.

**Comment by olivierlemasle** [comment]
Hi, I'm using latest vagrant and vagrant-hostmanager, and I have this issue with CoreOS.

Please find below my Vagrantfile and the error logs:


	test $# Vagrant and vagrant-hostmanager versions
	test $
	test $vagrant version
	Installed Version: 1.8.1
	Latest Version: 1.8.1
	 
	You're running an up-to-date version of Vagrant!
	test $
	test $vagrant plugin list
	vagrant-berkshelf (4.1.0)
	vagrant-cachier (1.2.1)
	vagrant-hostmanager (1.8.1)
	vagrant-libvirt (0.0.32)
	vagrant-mutate (1.1.0)
	vagrant-omnibus (1.4.1)
	vagrant-share (1.1.5, system)
	test $
	test $
	test $# VirtualBox version
	test $
	test $VBoxManage --version
	5.0.14r105127
	test $
	test $
	test $# Vagrantfile content
	test $
	test $cat Vagrantfile
	Vagrant.configure(2) do |config|

	  (1..2).each do |i|
	    hostname = "coreos-%02d" % i

	    config.vm.define hostname do |node|
		ip = "172.19.8.#{i+100}"
		node.vm.network "private_network", ip: ip
		node.vm.hostname = hostname
	    end
	  end

	  config.hostmanager.enabled = true
	  config.vm.box = "coreos-alpha"
	  config.vm.box_url = "https://storage.googleapis.com/alpha.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json"
	end
	test $
	test $vagrant up
	Bringing machine 'coreos-01' up with 'virtualbox' provider...
	Bringing machine 'coreos-02' up with 'virtualbox' provider...
	==> coreos-01: Importing base box 'coreos-alpha'...
	==> coreos-01: Matching MAC address for NAT networking...
	==> coreos-01: Checking if box 'coreos-alpha' is up to date...
	==> coreos-01: Setting the name of the VM: test_coreos-01_1456598255909_32499
	==> coreos-01: Clearing any previously set network interfaces...
	==> coreos-01: Preparing network interfaces based on configuration...
	    coreos-01: Adapter 1: nat
	    coreos-01: Adapter 2: hostonly
	==> coreos-01: Forwarding ports...
	    coreos-01: 22 (guest) => 2222 (host) (adapter 1)
	==> coreos-01: Running 'pre-boot' VM customizations...
	==> coreos-01: Booting VM...
	==> coreos-01: Waiting for machine to boot. This may take a few minutes...
	    coreos-01: SSH address: 127.0.0.1:2222
	    coreos-01: SSH username: core
	    coreos-01: SSH auth method: private key
	    coreos-01: Warning: Remote connection disconnect. Retrying...
	==> coreos-01: Machine booted and ready!
	==> coreos-01: Setting hostname...
	==> coreos-01: Configuring and enabling network interfaces...
	==> coreos-01: Updating /etc/hosts file on active guest machines...
	==> coreos-01: Forcing shutdown of VM...
	==> coreos-01: Destroying VM and associated drives...
	/opt/vagrant/embedded/gems/gems/net-scp-1.1.2/lib/net/scp/download.rb:103:in `parse_directive': unknown directive: "\u0001scp: /etc/hosts: No such file or directory\n" (ArgumentError)
		from /opt/vagrant/embedded/gems/gems/net-scp-1.1.2/lib/net/scp/download.rb:38:in `read_directive_state'
		from /opt/vagrant/embedded/gems/gems/net-scp-1.1.2/lib/net/scp.rb:363:in `block (3 levels) in start_command'
		from /home/olivier/.vagrant.d/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/channel.rb:324:in `call'
		from /home/olivier/.vagrant.d/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/channel.rb:324:in `process'
		from /home/olivier/.vagrant.d/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/session.rb:223:in `block in preprocess'
		from /home/olivier/.vagrant.d/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/session.rb:223:in `each'
		from /home/olivier/.vagrant.d/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/session.rb:223:in `preprocess'
		from /home/olivier/.vagrant.d/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/session.rb:206:in `process'
		from /home/olivier/.vagrant.d/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/session.rb:170:in `block in loop'
		from /home/olivier/.vagrant.d/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/session.rb:170:in `loop'
		from /home/olivier/.vagrant.d/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/session.rb:170:in `loop'
		from /home/olivier/.vagrant.d/gems/gems/net-ssh-3.0.2/lib/net/ssh/connection/channel.rb:269:in `wait'
		from /opt/vagrant/embedded/gems/gems/net-scp-1.1.2/lib/net/scp.rb:316:in `download!'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:253:in `block in download'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:630:in `block in scp_connect'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:312:in `connect'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:628:in `scp_connect'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/communicators/ssh/communicator.rb:252:in `download'
		from /home/olivier/.vagrant.d/gems/gems/vagrant-hostmanager-1.8.1/lib/vagrant-hostmanager/hosts_file/updater.rb:31:in `update_guest'
		from /home/olivier/.vagrant.d/gems/gems/vagrant-hostmanager-1.8.1/lib/vagrant-hostmanager/action/update_all.rb:35:in `block in call'
		from /home/olivier/.vagrant.d/gems/gems/vagrant-hostmanager-1.8.1/lib/vagrant-hostmanager/action/update_all.rb:32:in `each'
		from /home/olivier/.vagrant.d/gems/gems/vagrant-hostmanager-1.8.1/lib/vagrant-hostmanager/action/update_all.rb:32:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /home/olivier/.vagrant.d/gems/gems/vagrant-omnibus-1.4.1/lib/vagrant-omnibus/action/install_chef.rb:38:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/provision.rb:80:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /home/olivier/.vagrant.d/gems/gems/vagrant-cachier-1.2.1/lib/vagrant-cachier/action/configure_bucket_root.rb:20:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /home/olivier/.vagrant.d/gems/gems/vagrant-berkshelf-4.1.0/lib/vagrant-berkshelf/action/upload.rb:13:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /home/olivier/.vagrant.d/gems/gems/vagrant-berkshelf-4.1.0/lib/vagrant-berkshelf/action/install.rb:10:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /home/olivier/.vagrant.d/gems/gems/vagrant-berkshelf-4.1.0/lib/vagrant-berkshelf/action/save.rb:10:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/set_name.rb:50:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/box_check_outdated.rb:78:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/match_mac_address.rb:19:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/discard_state.rb:15:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/import.rb:74:in `import'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/import.rb:13:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/prepare_clone_snapshot.rb:17:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/prepare_clone.rb:15:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/customize.rb:40:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /home/olivier/.vagrant.d/gems/gems/vagrant-berkshelf-4.1.0/lib/vagrant-berkshelf/action/share.rb:10:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /home/olivier/.vagrant.d/gems/gems/vagrant-berkshelf-4.1.0/lib/vagrant-berkshelf/action/load.rb:10:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/env_set.rb:19:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /home/olivier/.vagrant.d/gems/gems/vagrant-berkshelf-4.1.0/lib/vagrant-berkshelf/action/check.rb:12:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:224:in `action_raw'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:199:in `block in action'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:561:in `lock'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `action'
		from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
	test $

**Comment by berndv** [comment]
same for me

**Comment by fateh22** [comment]
same error for me

**Comment by dal00** [comment]
Still an issue with Vagrant 2.1.5 and vagrant-hostmanager 1.8.9
