### ISSUE TITLE
Host and guest /etc/hosts ignore aliases

### ISSUE THREAD

**Issue by wizonesolutions** [smdahlen/vagrant-hostmanager#129]
````ruby
config.hostmanager.enabled = true
config.hostmanager.manage_host = true
config.hostmanager.ignore_private_ip = true # doesn't matter if this is set to true or false
config.vm.hostname = 'example.com'
config.hostmanager.aliases = [
  'example.com',
  'example.es',
]
````

Everything works fine, but:

1) The guest only get the hostname. It does not get the aliases.
2) The host doesn't get anything at all. I do see a "Checking hosts file" step flash by. Does that check pass when really it shouldn't?

I also tried running `vagrant hostmanager <global ID>`, but the results were the same.

I feel like I must be making a really dumb mistake, so pointing out of that would be greatly appreciated.

**Comment by wizonesolutions** [comment]
Update: Adding a private IP fixed the lack of provisioning of the host. This is probably a `vagrant-parallels` issue; its boxes have their own internal private IPs, but I guess `vagrant-hostmanager` wasn't able to see it unless I explicitly defined one. I'll ask them about it.

I'm still wondering why the aliases are not being processed properly.

**Comment by seth-reeser** [comment]
Appears to be resolved - please reopen if not the case.
