### ISSUE TITLE
Plugin does not trigger from box-embedded Vagrantfile

### ISSUE THREAD

**Issue by dkarlovi** [smdahlen/vagrant-hostmanager#131]
I've made [an example repo showing my plugin usage](https://github.com/dkarlovi/vagrant-playground). The `Vagrantfile` that gets embedded to the box being used is in `box` folder and the project-specific is in `project` folder.

The issue is, without reiterating

    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true

in the project config, hostmanager does not trigger on `vagrant up` or `vagrant hostmanager` even though it figures out the IP address, aliases and everything (debugged from running `vagrant hostmanager`). So I'm guessing it somehow loses the configuration, but cannot figure out how and where.

If I copy and paste these lines from box config to project config, it uses my `aliases` and `ip_resolver` properly so it does get those settings correctly.

**Comment by oddwheel** [comment]
+1 here
host - windows 7 x64
guest - ubuntu trusty64

**Comment by seth-reeser** [comment]
Please reopen if this is an issue with the latest version of Vagrant and vagrant-hostmanager.
