### ISSUE TITLE
Host aliases not being deleted on update

### ISSUE THREAD

**Issue by welly** [smdahlen/vagrant-hostmanager#132]
I updated my Vagrantfile changing the hostname. Checked /etc/hosts and noticed that the previous alias is still there:

```
## vagrant-hostmanager-start id: 99d40a63-852e-4be9-a3bc-d81a253c45cb
192.168.33.11	default.vagrant default.localdomain, default.dev
## vagrant-hostmanager-end

## vagrant-hostmanager-start id: a239ca5f-75ff-45a3-b0f5-15426ed77b94
192.168.33.11	largeformatphotography.vagrant default.localdomain, default.dev
## vagrant-hostmanager-end
```

Can confirm that the guest alias has been removed. This is Hostmanager 1.5.0 on OSX. It's not a critical issue but one probably worth looking at at some point!

Thanks!

**Comment by kodecraft** [comment]
I was having this problem as well. Flushing the DNS (ie., $ sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder) did not help.  I had to delete the extra entries before the new mappings started to work for me on OSX Mavericks 10.9.5.

**Comment by BrianGilbert** [comment]
What version of OSX were you using here?
As of 10.10 the correct command to flush dns is:
```
sudo discoveryutil udnsflushcaches
