### ISSUE TITLE
Windows  8.1 hosts file will only process 8 aliases per line

### ISSUE THREAD

**Issue by rockfreak** [smdahlen/vagrant-hostmanager#134]
Description:
When including more than 8 aliases into the host manager setting on vagrant only the first 8 aliases are recognised by windows.

// From vagrant file
config.hostmanager.aliases = %w(  url1.localhost www.url1.localhost url2.localhost www.url2.localhost url3.localhost www.url3.localhost url4.localhost www.url4.localhost url5.localhost www.url5.localhost )

// From the windows host file
## vagrant-hostmanager-start id: bb3ac214-ee02-48df-bc9a-a5775637ce78
192.168.33.2	devserver url1.localhost www.url1.localhost url2.localhost www.url2.localhost url3.localhost www.url3.localhost url4.localhost www.url4.localhost url5.localhost www.url5.localhost
## vagrant-hostmanager-end

Potential Fix:
If we can take the last to and make the windows hosts file look like this 

## vagrant-hostmanager-start id: bb3ac214-ee02-48df-bc9a-a5775637ce78
192.168.33.2	devserver url1.localhost www.url1.localhost url2.localhost www.url2.localhost url3.localhost www.url3.localhost url4.localhost www.url4.localhost
192.168.33.2  devserver url5.localhost www.url5.localhost
## vagrant-hostmanager-end

**Comment by rockfreak** [comment]
Ignore this it has been addressed in #103 and committed.

Any chance this can be bumped into a new version as I've have to apply the related commit my self (which works a treat by the way).

**Comment by danielbenzvi** [comment]
A version bump would be great.

**Comment by nick-pavluk** [comment]
Have the same issue

**Comment by natanael89** [comment]
+1

**Comment by seth-reeser** [comment]
This has been resolved with version 1.6.0
