### ISSUE TITLE
difference between what is installed and what is in this repo

### ISSUE THREAD

**Issue by chieroz** [smdahlen/vagrant-hostmanager#137]
sorry but I could not find a better description of the problem.

I work on a Mac with Yosemite 10.10.2. I installed this plugin with the normal procedure and I found that it refused to put each host on different lines on my machine /etc/hosts file.

I checked the issues on GitHub and after some fiddling I found that what is installed in 

`~/.vagrant.d/gems/gems/vagrant-hostmanager-1.5.0`

is different from the content of the same folder in this repo on GitHub. 

this is the structure in MY computer:

    ├── CHANGELOG.md
    ├── Gemfile
    ├── LICENSE.txt
    ├── README.md
    ├── Rakefile
    ├── lib
    │   ├── vagrant-hostmanager
    │   │   ├── action
    │   │   │   ├── update_all.rb
    │   │   │   ├── update_guest.rb
    │   │   │   └── update_host.rb
    │   │   ├── action.rb
    │   │   ├── command.rb
    │   │   ├── config.rb
    │   │   ├── errors.rb
    │   │   ├── hosts_file.rb
    │   │   ├── plugin.rb
    │   │   ├── provisioner.rb
    │   │   └── version.rb
    │   └── vagrant-hostmanager.rb
    ├── locales
    │   └── en.yml
    ├── test
    │   ├── Vagrantfile
    │   └── test.sh
    └── vagrant-hostmanager.gemspec
    
I tried to uninstall and reinstall the plugin but with no success. the only way to get the plugin to save each host of a MV on a different line was to just manually put the code I found on GitHub.

but of course this is NOT a very nice solution. is my computer looking for the plugin in an old repository?

thank you for your help

**Comment by seth-reeser** [comment]
I just released 1.6.0 that solves this problem, run `vagrant plugin update`
