### ISSUE TITLE
Linux hosts file is writen with CRLF line endings

### ISSUE THREAD

**Issue by la-magra** [smdahlen/vagrant-hostmanager#138]
I ran into a situation in which the the hosts file in the guest (ubuntu 14.04) had CRLF line endings when vagranted from a Windows server 2012 R2, with Vagrant 1.7.2 and hostmanager 1.5.0 . The vagrant commands where run from a cygwin shell.
As per Ruby documentation, I replaced open mode to binary since it "... suppresses EOL <-> CRLF conversion on Windows.", on the file hosts_file.rb:69.
That seems to resolve the issue (on this particular situation, untested on other guests).
I stand ready for further testing.

**Comment by seth-reeser** [comment]
This has been released. Thank you!

**Comment by xavierleune** [comment]
Hi,

I'm updating this issue beacuse I think it could have broke something. Actually, when you have a windows host and a linux guest, the linux host and the linux guest seems to have LF line endings.

Obviously, windows doesn't like LF too much :smiley: 
I have tested it under the release 1.6.1, vagrant command where run from the old-fashioned cmd tool.

Please let me know if I can provide more feedback.
PS : Many thanks @seth-reeser to keep this plugin going !
