### ISSUE TITLE
Unable to install due to FFI error

### ISSUE THREAD

**Issue by eapache** [smdahlen/vagrant-hostmanager#140]
Ubuntu 14.10 x64, vagrant 1.7.2, installation fails with:

```
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing ffi (1.9.8), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.8'` succeeds before bundling.

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /opt/vagrant/embedded/bin/ruby extconf.rb 
/opt/vagrant/embedded/bin/ruby: invalid option -M  (-h will show valid options) (RuntimeError)


Gem files will remain installed in /media/eapache/Media/Virtual Machines/Vagrant/gems/gems/ffi-1.9.8 for inspection.
Results logged to /media/eapache/Media/Virtual Machines/Vagrant/gems/gems/ffi-1.9.8/ext/ffi_c/gem_make.out
```

The ruby ffi package from ubuntu is already installed, but I guess it's not being used because vagrant packages its own - I'm not sure what else to try here.

**Comment by eapache** [comment]
Turns out this is due to the space in my vagrant path - removing it fixed the issue. Not sure if I should refile this against vagrant or ffi or something, but clearly something should be escaping that path string along the way.

**Comment by jpmurray** [comment]
@eapache I'm getting the very same error, although, echo $PATH won't show anything with spaces in it. How did you solve your own problem exactly?

**Comment by eapache** [comment]
The path used by vagrant is different from `$PATH` - in the last line (results logged to...) look for a space there.

E.g. in my case, the error was "invalid option -M" because the first letter after the space in my vagrant directory (`/media/eapache/Media/Virtual Machines/Vagrant/`) is "M" for "Machines".

**Comment by jpmurray** [comment]
@eapache thanks for that. Probably didn't get enough coffee, but the error isn't exactly the same after all... And every plugins install throws me the same now.

    Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /opt/vagrant/embedded/bin/ruby extconf.rb 
    checking for ffi.h... *** extconf.rb failed ***
    Could not create Makefile due to some reason, probably lack of necessary
    libraries and/or headers.  Check the mkmf.log file for more details.  You may
    need configuration options.

    /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:434:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
    You have to install development tools first.
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:549:in `block in try_compile'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:502:in `with_werror'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:549:in `try_compile'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:1044:in `block in have_header'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:895:in `block in checking_for'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:340:in `block (2 levels) in postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:340:in `block in postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:310:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:336:in `postpone'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:894:in `checking_for'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:1043:in `have_header'
	from extconf.rb:16:in `<main>'


    Gem files will remain installed in /Users/webdev/.vagrant.d/gems/gems/ffi-1.9.8 for inspection.
    Results logged to /Users/webdev/.vagrant.d/gems/gems/ffi-1.9.8/ext/ffi_c/gem_make.out
    Bundler, the underlying system Vagrant uses to install plugins,
    reported an error. The error is shown below. These errors are usually
    caused by misconfigured plugin installations or transient network
    issues. The error from Bundler is:

    An error occurred while installing ffi (1.9.8), and Bundler cannot continue.
    Make sure that `gem install ffi -v '1.9.8'` succeeds before bundling.



Gem files will remain installed in /Users/webdev/.vagrant.d/gems/gems/ffi-1.9.8 for inspection.
Results logged to /Users/webdev/.vagrant.d/gems/gems/ffi-1.9.8/ext/ffi_c/gem_make.out
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing ffi (1.9.8), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.8'` succeeds before bundling.

**Comment by jpmurray** [comment]
To anyone who could get the above error (mine, not @eapache): I was working on a brand new iMac and I installed Xcode... Without opening it. You need to accept the license agreement Xcode pops when you first open it and then installing plugins works.

**Comment by amarkpark** [comment]
@jpmurray THANK YOU!
