### ISSUE TITLE
Way to inspect vhosts of guest and add entries to /etc/hosts file on host OS?

### ISSUE THREAD

**Issue by BrianGilbert** [smdahlen/vagrant-hostmanager#141]
Wondering if there is a way that this could be done?

considerations: apache and nginx..

**Comment by sman591** [comment]
+1, would love this as a feature

**Comment by seth-reeser** [comment]
How are you making these vhosts? If the vhosts are scripted, you can script the aliases to be added. Check out https://github.com/devopsgroup-io/catapult-release-management
