### ISSUE TITLE
Remove host machine lines when `vagrant suspend` or `vagrant halt` are called

### ISSUE THREAD

**Issue by markjaquith** [smdahlen/vagrant-hostmanager#143]
vagrant-hostmanager maintains the host machine's `/etc/hosts` lines after `vagrant suspend` or `vagrant halt` are called. This seems like terrible behavior. Why maintain the lines if the guest is powered down?

**Comment by utrotzek** [comment]
This has already been discussed in #56

**Comment by krak3n** [comment]
@markjaquith perhaps you should use https://github.com/cogitatio/vagrant-hostsupdater - it seems to hook in with those events fine.

**Comment by EvanK** [comment]
For reference, hostsupdater is [accomplishing this by hooking into several machine actions](https://github.com/cogitatio/vagrant-hostsupdater/blob/bb1a4955b1be46173b3cea5abe02586f0f82325f/lib/vagrant-hostsupdater/plugin.rb#L19-L45) and calling its own operation-specific actions.

It's worth noting, however, that hostmanager also has to manage the _guest_ hostfile, and in doing so adds significant complexity to everything it does.

**Comment by seth-reeser** [comment]
This workflow would create an inconsistent environment state. This would be compared to having production DNS go away when a production web server went down. You're reaching too far into TCP/IP for this to be considered best practice DevOps.

**Comment by nathanielks** [comment]
> This would be compared to having production DNS go away when a production web server went down.

@seth-reeser _exactly_. And even by keeping the entries in `/etc/hosts`, it'll still behave the same way because the hosts aren't up. Either way: when the machines are down, the ip recorded in the host file isn't usable, so there's no sense in keeping in `/etc/hosts`.

**Comment by seth-reeser** [comment]
@nathanielks sorry - I do not agree. I do appreciate the feedback, though.

**Comment by nathanielks** [comment]
Can you rebut? I'm really interested in hearing how it would differ from a real production environment.

**Comment by seth-reeser** [comment]
I believe you misunderstood my comment:

> This would be compared to having production DNS go away when a production web server went down.

I meant DNS being removed - at the core of DevOps is replication. Please use this as a thought example:

You have a Vagrant environment defined with a local Apache and MySQL server running Drupal - forgetting that the MySQL server is halted (and in this case the DNS for the MySQL server non-existent) you now have to troubleshoot differently then you would in an upstream environment. You would be experiencing a DNS resolution error vs a timeout.

Make sense? It may seem extreme and not ideal - BUT exacting environments trump (no current event pun intended) convenience.
