### ISSUE TITLE
Maxitems on Windows hosts in /etc/hosts file

### ISSUE THREAD

**Issue by utrotzek** [smdahlen/vagrant-hostmanager#144]
On windows (tested on Windows 7) hosts there can only be 10 items per line incl. IP. Please split the line into multiple rows if there are more items.

How to test:
#/etc/hosts
2.3.4.5 testurl1.test.de testurl2.test.de testurl3.test.de testurl4.test.de testurl5.test.de testurl6.test.de testurl7.test.de testurl8.test.de testurl9.test.de testurl10.test.de

testurl10.test.de doesn't work
everything from testurl1 to testurl9 works like a charm

**Comment by seth-reeser** [comment]
v1.6.0 has been released which resolves this issue.

**Comment by utrotzek** [comment]
I installed v1.6.0 and tested with the following config: 

default_config.vm.hostname = testhostname
default_config.hostmanager.aliases = "domain1.test.de domain2.test.de domain3.test.de domain4.test.de domain5.test.de domain6.test.de domain7.test.de domain8.test.de domain9.test.de domain10.test.de domain11.test.de domain12.test.de domain13.test.de domain14.test.de domain15.test.de domain16.test.de"

The Output in /etc/hosts on my host system is:

## vagrant-hostmanager-start id: 927f569e-b721-4b40-8a01-0e2a68c17256
2.3.4.5	testhostname
2.3.4.5	domain1.test.de domain2.test.de domain3.test.de domain4.test.de domain5.test.de domain6.test.de domain7.test.de domain8.test.de domain9.test.de domain10.test.de domain11.test.de domain12.test.de domain13.test.de domain14.test.de domain15.test.de domain16.test.de
## vagrant-hostmanager-end

Am I doing something wrong?

**Comment by seth-reeser** [comment]
Please run `vagrant hostmanager` from the command line and paste your output here.

**Comment by utrotzek** [comment]
That's exactly what I did before I posted the content of the hosts file. :(

**Comment by seth-reeser** [comment]
`vagrant hostmanager` is running without outputting any errors? You could try running `vagrant destroy` then `vagrant up`.

**Comment by seth-reeser** [comment]
Ah, I completely overlooked this, your default_config.hostmanager.aliases should be an array, you just have spaces separating them.

**Comment by utrotzek** [comment]
Sorry for the delay, I was on vacation. 

Thank you very much, it's works like a charm. I'm not very familiar with ruby syntax so I would've never found the issue. ;)
