### ISSUE TITLE
Vagrant on Ubuntu 15.04 network interfaces.

### ISSUE THREAD

**Issue by jarrettj** [smdahlen/vagrant-hostmanager#146]
Hi,

Good day.

Since upgrading to Ubuntu 15.04 the vagrant network interface does not persist when coming out of suspend.

```
Repro:
vagrant up # I use hostmanager to handle hosts file
# Browsing to test site works
vagrant suspend # Suspend environment
vagrant up # Bring out of suspended state
# Browsing to test site does not work
```

You will not be able to access your test site. The network interface is gone. You have to reload the entire environment and run vagrant hostmanager again to get to your test sites.

This happens when you suspend your system as well.

Cheers.

**Comment by conorsch** [comment]
Looks like this may be an [upstream bug in the VirtualBox](https://bugs.launchpad.net/ubuntu/+source/virtualbox/+bug/1460750), see recent discussion on mitchellh/vagrant#5689.

**Comment by seth-reeser** [comment]
Hi @jarrettj, @conorsch is on the right track, this has to do with the network interface dropping at the VirtualBox level and not the hosts file.

**Comment by jarrettj** [comment]
Cool. I'm getting use to doing a vagrant reload. No worries :)
