### ISSUE TITLE
hostmanager prevent defintiion of guest FQDN

### ISSUE THREAD

**Issue by pbuyle** [smdahlen/vagrant-hostmanager#147]
The line added by hostmanager to /etc/hosts in the guest does is not compatyible on what Ubuntu expect to find in order to be able to set the FQDN of the guest.

According to the `hostname` man page, the loigne should looks like `127.0.1.1    ursula.example.com ursula`. But when using hostmanager with an alias, the line looks like `127.0.1.1    ursula ursula.example.com`.

**Comment by seth-reeser** [comment]
This should be resolved now with version v1.6.0 as it splits hosts onto separate lines.
