### ISSUE TITLE
Password Prompt

### ISSUE THREAD

**Issue by simkessy** [smdahlen/vagrant-hostmanager#152]
Is there a way to bypass it asking for a password whenever I run `vagrant up`

**Comment by tommygnr** [comment]
@simkessy See [here](https://github.com/smdahlen/vagrant-hostmanager#passwordless-sudo) in the readme

**Comment by seth-reeser** [comment]
Please see https://github.com/smdahlen/vagrant-hostmanager#passwordless-sudo
