### ISSUE TITLE
1.6.0 not published

### ISSUE THREAD

**Issue by sadams** [smdahlen/vagrant-hostmanager#155]
could you publish it pls? the Mac bug in hosts file is driving me nuts!

**Comment by seth-reeser** [comment]
Waiting for @smdahlen to provide me access to https://rubygems.org/gems/vagrant-hostmanager

**Comment by seth-reeser** [comment]
I was just given access, 1.6.0 has been published! Let the one line aliases commence.

**Comment by sadams** [comment]
worked perfectly, thanks!

**Comment by seth-reeser** [comment]
@sadams awesome! glad to hear.
