### ISSUE TITLE
aliases_on_separate_lines doesn't seem to work

### ISSUE THREAD

**Issue by MarcoDeBortoli** [smdahlen/vagrant-hostmanager#156]
Hey there, I followed the documentation and also the test Vagrantfile present in your source but it doesn't look like the flag works. The aliases don't get split and still written in one single line. I'm on the latest version of yosemity and vagrant, what could be the cause of this? What additional information do you need from me to better understand what the possible cause can be?

**Comment by seth-reeser** [comment]
Hello, the newest release of vagrant-hostmanager, 1.6.0, splits the aliases on seperate lines. Make sure you run vagrant plugin update, then run vagrant hostmanager to update your hosts file. The flag is meant for the next release.

**Comment by MarcoDeBortoli** [comment]
I thought it was already part of 1.5 accordingly to the documentation. Thanks for the heads up

**Comment by MarcoDeBortoli** [comment]
Ok, updated and checked. All working fine now. Thanks a lot.
