### ISSUE TITLE
/etc/hosts file on guest is left with incorrect permissions

### ISSUE THREAD

**Issue by 4nd** [smdahlen/vagrant-hostmanager#160]
Vagrant: 1.7.4
Hostmanager: 1.6.0
Provider: Virtualbox 5.0.0
Host OS: OSX 10.10.4
Guest OS: Ubuntu 14.04

I recently noticed this happening and can't work out whats up, the same Vagrantfile was working and now its not.  I've only updated to virtual box 5 and host manager 1.6 in an attempt to fix the issue.  No different.

-rw------- 1 vagrant vagrant 342 Aug  6 15:57 /etc/hosts

If disable the plugin the hosts file permissions are fine.  Even existing boxes that were working before are now failing due to this problem.  When this happens the hosts file is not readable by php, hence my hostname lookups fail.

Any ideas?

**Comment by erikhakansson** [comment]
I have this issue to. I get permission 700 with owner vagrant:vagrant. If I manually fix the permissions and chown to root everything works.

A workaround is to add the following provision to your vagrantfile:

~~~
  #the vagrant-hostmanager plugin has a bug where ownership and permissions for the guest /etc/hosts file will be changed. This workaround changes it back:
  config.vm.provision "fix-hostmanager-bug", type: "shell", run: "always" do |s|
    s.inline = <<-EOT
    sudo restorecon /etc/hosts
    sudo chown root:root /etc/hosts
    sudo chmod 644 /etc/hosts
    EOT
  end
~~~

**Comment by organsnyder** [comment]
I'm encountering this issue as well with a centos/7 guest. When I try to do anything as root, the hosts file is ignored unless I change the ownership back to root. I'm assuming that this is a security precaution—if the hosts file is writable by someone other than root, then the root account shouldn't use it.

**Comment by organsnyder** [comment]
@seth-reeser Why was this issue marked "more information needed"?

**Comment by seth-reeser** [comment]
This is a small insight into the overall issue - there are n operating systems that are taken into account. We're always looking for volunteers to address the issue and create a pull request.

**Comment by tonylambiris** [comment]
I believe the main issue being discussed is line 44 of updater.rb is what changes the SElinux context of /etc/hosts. By default on CentOS/7 the following context is used for /etc/hosts:
```shell
# ls -laZ /etc/hosts
-rw-r--r--. root root system_u:object_r:net_conf_t:s0  /etc/hosts
```

Because the hostmanager plugin is moving a file from /tmp to /etc it will also carry over with it the context established when the file was created in /tmp:
```shell
17:16:07 master ~ # cat /etc/hosts > /tmp/hosts.tmp
17:16:17 master ~ # ls -laZ /tmp/hosts.tmp
-rw-r--r--. root root unconfined_u:object_r:user_tmp_t:s0 /tmp/hosts.tmp
17:16:23 master ~ # ls -laZ /etc/hosts
-rw-r--r--. root root system_u:object_r:net_conf_t:s0  /etc/hosts
17:16:36 master ~ # mv /tmp/hosts.tmp /etc/hosts
mv: overwrite ‘/etc/hosts’? y
17:16:50 master ~ # ls -laZ /etc/hosts
-rw-r--r--. root root unconfined_u:object_r:user_tmp_t:s0 /etc/hosts
```

This interferes with the default selinux-policy rules on CentOS/7 if you use dnsmasq for a local caching nameserver:
```shell
type=AVC msg=audit(1453224496.765:1142): avc:  denied  { open } for  pid=9316 comm="dnsmasq" path="/etc/hosts" dev="dm-0" ino=14822337 scontext=system_u:system_r:dnsmasq_t:s0 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=file permissive=0
```

The correct SElinux context can be shown/restored with the following command:
```shell
17:16:51 master ~ # restorecon -v /etc/hosts
restorecon reset /etc/hosts context unconfined_u:object_r:user_tmp_t:s0->unconfined_u:object_r:net_conf_t:s0
17:18:04 master ~ # ls -laZ /etc/hosts
-rw-r--r--. root root unconfined_u:object_r:net_conf_t:s0 /etc/hosts
```

It appears the fix is one of two options that both would involve changes to updated.rb -- either add the -Z flag in the move_cmd variable on line 30 or apply the following patch:
```diff
--- updater.rb.dist	2016-01-19 01:57:25.000000000 -0500
+++ updater.rb	2016-01-19 12:29:58.000000000 -0500
@@ -38,10 +38,8 @@
             machine.communicate.upload(file, '/tmp/hosts')
             if windir
               machine.communicate.sudo("#{move_cmd} /tmp/hosts/hosts.#{machine.name} #{realhostfile}")
-            elsif machine.communicate.test('test -f /.dockerinit')
-              machine.communicate.sudo("cat /tmp/hosts > #{realhostfile}")
             else
-              machine.communicate.sudo("#{move_cmd} /tmp/hosts #{realhostfile}")
+              machine.communicate.sudo("cat /tmp/hosts > #{realhostfile}")
             end
           end
```
