### ISSUE TITLE
Vagrant up no longer works after plugin install

### ISSUE THREAD

**Issue by domenicbove** [smdahlen/vagrant-hostmanager#162]
Hi, I am new to the plugin so I do not mean to offend. I'll just show what I enter into the terminal

$ vagrant plugin install vagrant-hostmaster
Installing the 'vagrant-hostmaster' plugin. This can take a few minutes...
Installed the plugin 'vagrant-hostmaster (0.6.2)'!

vagrant up --no-provision
Vagrant failed to initialize at a very early stage:

The plugins failed to load properly. The error message given is
shown below.

cannot load such file -- vagrant/command

Now when I uninstall the plugin, I can start using vagrant again...
Any ideas? I would like to use the plugin!

**Comment by domenicbove** [comment]
Somehow ended up w an outdated version, sorry

**Comment by soundarmoorthy** [comment]
I installed vagrant-hostmaster instead of installing vagrant-hostmanager :P. After removing vagrant-hostmaster things worked fine. I guess the 0.6.2 version of the plugin has issues by defualt ?
