### ISSUE TITLE
Consider making the new manage_guest setting true by default

### ISSUE THREAD

**Issue by rbarlow** [smdahlen/vagrant-hostmanager#177]
I'm not a Ruby dev so I may be reading the code wrong, but it seems to me that the behavior in 1.7.1 was to always manage the guest's hosts file and it seems that in 1.8.0 it only manages it if the user explicitly defines a setting. I'm basing that on the default:

https://github.com/smdahlen/vagrant-hostmanager/blob/6f4c0d7c6a5f2365e1353f7fec08950a5c874c3c/lib/vagrant-hostmanager/config.rb#L30

This would make 1.8.0 backwards-incompatible with 1.7.1 which some users may find surprising since it's a Y release. Would you consider swapping the default to true and releasing a 1.8.1 with that, (assuming that I've interpreted the code correctly? Apologies if I am mistaken…)

**Comment by seth-reeser** [comment]
@rbarlow you are correct! That's what I get for releasing software early in the morning - look out for v1.8.1 shortly.

**Comment by rbarlow** [comment]
Thanks @seth-reeser, and no worries. I've enjoyed using your software, thanks for making it Free!

**Comment by seth-reeser** [comment]
Glad to hear it! v1.8.1 release - https://rubygems.org/gems/vagrant-hostmanager/versions/1.8.1

**Comment by rbarlow** [comment]
@seth-reeser Thanks again for making the release! You may want to tag it here in github too. Now on to packaging it for Fedora!
