### ISSUE TITLE
Getting a Vagrant error when setting include_offline to false

### ISSUE THREAD

**Issue by c4milo** [smdahlen/vagrant-hostmanager#21]
"The machine with the name 'default' was not found configured for this Vagrant environment."

``` ruby
config.hostmanager.enabled = true
config.hostmanager.ignore_private_ip = false
config.hostmanager.include_offline = false
config.vm.provision :hostmanager
```

The name of my machine is superbox by the way, no "default". 

Any idea what I might be doing wrong?

**Comment by aprudnik** [comment]
Thanks @uatec!
