### ISSUE TITLE
Adding multiple virtual hosts

### ISSUE THREAD

**Issue by nddery** [smdahlen/vagrant-hostmanager#32]
I've enabled multiple virtual hosts on the VM by adding the following to a file called `default` in `/etc/apache2/sites-available/`. This file is symlinked to `/etc/apache2/sites-enabled/000-default`.

```
NameVirtualHost *:80

<VirtualHost *:80>
   ServerName default.com
   DocumentRoot "/vagrant/vhosts/default/httpdocs"
   <Directory />
      Options Indexes FollowSymLinks
      AllowOverride All
   </Directory>
</VirtualHost>

<VirtualHost *:80>
   ServerName dev.default.com
   DocumentRoot "/vagrant/vhosts/default/dev"
   <Directory />
      Options Indexes FollowSymLinks
      AllowOverride All
   </Directory>
</VirtualHost>
```

Manually editing my host `/etc/hosts/` file to add these two line, I can access both virtual hosts at `http://default.com:8080` and `http://dev.default.com:8080` respectively. However, for this to work, I have to manually edit my host hosts file.

Lines manually added to `/etc/hosts` on host computer:

```
127.0.0.1 default.com
127.0.0.1 dev.default.com
```

vagrant-hostmanager does add this line to `/etc/hosts` on host computer:

```
127.0.0.1 default #bunch of numbers
```

Is there a way to have multiple virtual hosts added to `/etc/hosts` automatically ?

My `Vagrantfile` looks like so, maybe I should be adding something ?

```
Vagrant.configure("2") do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.network :forwarded_port, guest: 80, host: 8080

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.module_path = "puppet/modules"
    puppet.manifest_file  = "init.pp"
    puppet.options="--verbose --debug"
  end
end
```

Thanks!

**Comment by vitoleefilm** [comment]
hi, I just want to ask if I need to modify my own hosts file after adding the line to  Vagrantfile?
