### ISSUE TITLE
call remove hosts on vagrant halt

### ISSUE THREAD

**Issue by utrotzek** [smdahlen/vagrant-hostmanager#56]
Hi,

I'd suggest to call the hosts cleanup task also on vagrant halt in addition to vagrant destroy. Because if the vm is down, the host entries don't make sense (in my opinion)

This would be similar to vagrant's core behaviour for the host entry.

Thanks for sharing this ext! ;)

kind regards

**Comment by krak3n** [comment]
https://github.com/cogitatio/vagrant-hostsupdater - seems to handle it fine.
