### ISSUE TITLE
hostmanager incompatible with :public_network

### ISSUE THREAD

**Issue by jberkus** [smdahlen/vagrant-hostmanager#63]
When I set my configuration to :private_network, I get the following in /etc/hosts on each VM:

192.168.199.202 paul paul.test.com  
192.168.199.201 john john.test.com  
192.168.199.203 george george.test.com  

However, if I set vm.network to :public_network, changing nothing else, I get this:

127.0.0.1 paul paul.test.com  
127.0.0.1 john john.test.com  
127.0.0.1 george george.test.com  

Not sure what's going wrong there.

**Comment by rastasheep** [comment]
Tnx for the snippets! 

I think it should be added to some more public place (if it will not be added as feature), it seems that this is pretty common use case.

**Comment by xooooooooox** [comment]
> @pbitty Nice ip_resolver snippet above! Your regexp doesn't match on a few of my vms (due to localization of the ifconfig output). I modified it a little bit to be more robust...
> 
> ```ruby
> (ip = /^\s*inet .*?(\d+\.\d+\.\d+\.\d+)\s+/.match(result)) && ip[1]
> ```
> 
> Full snippet (for lazy copy & paste guys):
> 
> ```ruby
>   config.hostmanager.ip_resolver = proc do |machine|
>     result = ""
>     machine.communicate.execute("ifconfig eth1") do |type, data|
>       result << data if type == :stdout
>     end
>     (ip = /^\s*inet .*?(\d+\.\d+\.\d+\.\d+)\s+/.match(result)) && ip[1]
>   end
> ```

I use hostmanager as **provisioner**, 
how to transfer this snippet？

**Comment by pbitty** [comment]
@xozoz , I am not sure what you mean.  Could you expand on what you are trying to do?
